/*
 * GuessView.java
 */
package guess;

import java.util.Scanner;
import javax.swing.Icon;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

import javax.swing.JDialog;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class GuessView extends FrameView {

    public GuessView(SingleFrameApplication app) {
        super(app);

        initComponents();
        LimitedDocument lDoc = new LimitedDocument(9);
        lDoc.setAllowChar(new String("0123456789"));
        jTxtNum.setDocument(lDoc);
        numGuess.newGame();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = GuessApp.getApplication().getMainFrame();
            aboutBox = new GuessAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        GuessApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jBtnGo = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jLblInfo = new javax.swing.JLabel();
        jTxtNum = new javax.swing.JTextField();
        jLblMsg = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu gameMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        ansMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(guess.GuessApp.class).getContext().getResourceMap(GuessView.class);
        jBtnGo.setText(resourceMap.getString("jBtnGo.text")); // NOI18N
        jBtnGo.setName("jBtnGo"); // NOI18N
        jBtnGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGoMouseClicked(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(guess.GuessApp.class).getContext().getActionMap(GuessView.class, this);
        jBtnExit.setAction(actionMap.get("quit")); // NOI18N
        jBtnExit.setText(resourceMap.getString("jBtnExit.text")); // NOI18N
        jBtnExit.setName("jBtnExit"); // NOI18N

        jLblInfo.setText(resourceMap.getString("jLblInfo.text")); // NOI18N
        jLblInfo.setName("jLblInfo"); // NOI18N

        jTxtNum.setText(resourceMap.getString("jTxtNum.text")); // NOI18N
        jTxtNum.setName("jTxtNum"); // NOI18N

        jLblMsg.setText(resourceMap.getString("jLblMsg.text")); // NOI18N
        jLblMsg.setName("jLblMsg"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNum, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jLblMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblMsg)
                            .addComponent(jBtnExit)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jBtnGo)
                        .addGap(33, 33, 33)))
                .addGap(10, 10, 10))
        );

        menuBar.setName("menuBar"); // NOI18N

        gameMenu.setText(resourceMap.getString("gameMenu.text")); // NOI18N
        gameMenu.setName("gameMenu"); // NOI18N

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setIcon(resourceMap.getIcon("newMenuItem.icon")); // NOI18N
        newMenuItem.setText(resourceMap.getString("newMenuItem.text")); // NOI18N
        newMenuItem.setToolTipText(resourceMap.getString("newMenuItem.toolTipText")); // NOI18N
        newMenuItem.setName("newMenuItem"); // NOI18N
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(newMenuItem);

        ansMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        ansMenuItem.setText(resourceMap.getString("ansMenuItem.text")); // NOI18N
        ansMenuItem.setToolTipText(resourceMap.getString("ansMenuItem.toolTipText")); // NOI18N
        ansMenuItem.setName("ansMenuItem"); // NOI18N
        ansMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(ansMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gameMenu.add(jSeparator1);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setToolTipText(resourceMap.getString("exitMenuItem.toolTipText")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        gameMenu.add(exitMenuItem);

        menuBar.add(gameMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGoMouseClicked
        // TODO add your handling code here:
        String str = new String(jTxtNum.getText());
        if (str.equals("")) {
            //jLblMsg.setText("Please input a number.");
            JOptionPane.showMessageDialog(null, "Please input a number.");
        } else {
            Scanner sc = new Scanner(str);
            long ret = numGuess.Guess(sc.nextLong());
            if (ret > 0) {
                //jLblMsg.setText("Large");
                JOptionPane.showMessageDialog(null, "too large");
            } else if (ret < 0) {
                //jLblMsg.setText("Small");
                JOptionPane.showMessageDialog(null, "too small");
            } else {
                //jLblMsg.setText("Congratulations, you guess it");
                String msg = new String();
                msg = String.format("Congratulations, you guess it. Totally %d guesses",
                        numGuess.getCount());
                JOptionPane.showMessageDialog(null, msg);
            }
        }
        return;
    }//GEN-LAST:event_jBtnGoMouseClicked

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        numGuess.newGame();
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void ansMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansMenuItemActionPerformed
        String msg = new String();
        msg = String.format("the answer is %d.", numGuess.getAnswer());
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_ansMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ansMenuItem;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnGo;
    private javax.swing.JLabel jLblInfo;
    private javax.swing.JLabel jLblMsg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtNum;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    // End of variables declaration//GEN-END:variables
    private int busyIconIndex = 0;
    private JDialog aboutBox;
    private Game numGuess = new Game();
}
